development:
  forest_env_secret: f384f735eee6cd188842e8a4cf3b087e12ce08d859476b12978538e434cf1d3a
  forest_auth_secret: 2soRVdmI03w-FHY5xIQULw
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
